# Generated by Django 4.2.4 on 2023-08-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2002-03-05'),
            preserve_default=False,
        ),
    ]
